version: "3.7"

services:
  nginx:
    image: aprendendolinux/nginx:latest
    restart: always
    container_name: nginx
    volumes:
    - nginx:/var/www/html
    ports:
    - "80:80"
volumes:
  nginx:
